spring.application.name=New_Retail_Management_System_Back
spring.datasource.url=jdbc:mysql://localhost:3306/retailsystem
spring.datasource.username=root
spring.datasource.password=Pooja@1234
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver


cloudinary.cloud_name=dbxrly4ci
cloudinary.api_key=791896861245918
cloudinary.api_secret=_8rODTdgUhEnQhgkyZuox6u0fUE